baseURL = 'https://ertuil.github.io/QuantumNetworkWebSite/'
languageCode = 'en-us'
title = 'Group of Quantum Network, USTC'
theme = 'timer-hugo'
enableEmoji = true
paginate = "5"

[params]
home = "Home"
#logo = "images/ustc.jpg"
dateFormat = "6 January 2006"
# Meta data
description = "Our research group focusing quantum networks"
author = "Infolab, USTC"
# Google Analitycs
#googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable = true
bgImage = "images/slider.jpg"
heading = "We are a group of passinate perple, focus on"
description = "We try to propose a brand new network architecture, leverage the quantum information science, to build a BETTER, SECURE, and POWERFUL quantum network."
# button
btn = false
btnText = "Download More"
btnURL = "https://themefisher.com/"

# flip text
[[params.banner.flipText]]
title = "Quantum Networks"
[[params.banner.flipText]]
title = "Quantum Internet"
[[params.banner.flipText]]
title = "Cyber Security"

# Homepage About Section
[params.about]
enable = true
title = "ABOUT US"
content = "TBD! Under construction!"
image = "images/team.png"

# Call to Action
[params.cta]
enable = true
title = "Welcome to contact us"
content = "We would be gald to hear your comments and suggestions. Click the following button to email us."
btnText = "Contact Us"
btnURL = "mailto:kpxue@ustc.edu.cn"

# Portfolio Section On Homepage
[params.portfolio]
enable = true
title = "Latest Works"
subtitle = "Here are some recent works, papers, and other recent situation of our team."

# social icon
# [[params.socialIcon]]
# icon = "ion-social-ma"
# url = "#"

[[params.socialIcon]]
icon = "ion-social-mail"
url = "#"

# [[params.socialIcon]]
# icon = "ion-social-linkedin"
# url = "#"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Our Work"
    url = "work/"
    weight = 3

[[menu.main]]
    name = "Simulator"
    url = "simulator/"
    weight = 4

[[menu.main]]
    name = "Blog"
    url = "blog/"
    weight = 5

[[menu.main]]
    url = "about/"
    name = "About Us"
    weight = 6